// Inline-style objects shared by ProposalView and its extracted sections.
// Originally lived inside ProposalView.js as a `const styles = {...}` block;
// hoisted here so the extracted child components can import them without
// prop-drilling. No values changed — all keys + values are byte-identical
// to the pre-refactor const.

const styles = {
  page: {
    minHeight: '100vh',
    background: 'linear-gradient(180deg, #faf5ef 0%, #f5ede0 100%)',
    padding: '2rem 1rem',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  container: {
    maxWidth: '680px',
    margin: '0 auto',
    background: '#fff',
    borderRadius: '12px',
    boxShadow: '0 4px 24px rgba(58, 34, 24, 0.1)',
    overflow: 'hidden',
  },
  header: {
    textAlign: 'center',
    padding: '2.5rem 2rem 1.5rem',
    borderBottom: '1px solid #e8e0d4',
  },
  brand: {
    fontFamily: 'Georgia, "Times New Roman", serif',
    fontSize: '2rem',
    color: '#3a2218',
    margin: 0,
  },
  tagline: {
    color: '#8b7355',
    marginTop: '0.3rem',
    fontSize: '1rem',
    letterSpacing: '0.05em',
  },
  section: {
    padding: '1.5rem 2rem',
    borderBottom: '1px solid #e8e0d4',
  },
  sectionTitle: {
    fontFamily: 'Georgia, "Times New Roman", serif',
    fontSize: '1.2rem',
    color: '#3a2218',
    marginBottom: '1rem',
    marginTop: 0,
  },
  heading: {
    fontFamily: 'Georgia, "Times New Roman", serif',
    fontSize: '1.5rem',
    color: '#3a2218',
  },
  detailGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '0.75rem',
  },
  detailItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.2rem',
  },
  detailLabel: {
    fontSize: '0.75rem',
    color: '#8b7355',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  detailValue: {
    fontSize: '0.95rem',
    color: '#3a2218',
    fontWeight: 500,
  },
  includesList: {
    margin: 0,
    padding: '0 0 0 1.2rem',
    color: '#6b4226',
  },
  includesItem: {
    fontSize: '0.9rem',
    marginBottom: '0.3rem',
  },
  contractScroll: {
    maxHeight: '300px',
    overflowY: 'auto',
    background: '#faf5ef',
    border: '1px solid #e8e0d4',
    borderRadius: '8px',
    padding: '1.25rem',
  },
  contractText: {
    fontSize: '0.875rem',
    color: '#4a3520',
    lineHeight: 1.6,
    marginBottom: '0.75rem',
    marginTop: 0,
  },
  contractList: {
    margin: '0 0 0.75rem 0',
    padding: '0 0 0 1.2rem',
    color: '#4a3520',
  },
  contractListItem: {
    fontSize: '0.875rem',
    lineHeight: 1.6,
    marginBottom: '0.35rem',
  },
  paymentSummary: {
    background: '#faf5ef',
    border: '1px solid #e8e0d4',
    borderRadius: '8px',
    padding: '0.25rem 1.25rem',
  },
  paymentRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.75rem 0',
    borderBottom: '1px solid #e8e0d4',
  },
  paymentLabel: {
    fontSize: '0.9rem',
    color: '#6b4226',
  },
  paymentValue: {
    fontSize: '0.95rem',
    fontWeight: 600,
    color: '#3a2218',
  },
  ctaButton: {
    display: 'block',
    width: '100%',
    marginTop: '1.25rem',
    padding: '1rem',
    background: '#2d6a4f',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    fontSize: '1.1rem',
    fontWeight: 700,
    cursor: 'pointer',
    letterSpacing: '0.02em',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  signPaySection: {
    padding: '2rem',
    background: '#f9f5ef',
    borderBottom: '1px solid #e8e0d4',
  },
  signPayTitle: {
    fontFamily: 'Georgia, "Times New Roman", serif',
    fontSize: '1.3rem',
    color: '#2d6a4f',
    marginBottom: '0.25rem',
    marginTop: 0,
  },
  label: {
    display: 'block',
    fontSize: '0.8rem',
    fontWeight: 600,
    color: '#6b4226',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    marginBottom: '0.4rem',
  },
  nameInput: {
    width: '100%',
    padding: '0.6rem 0.75rem',
    border: '1px solid #d4c4b0',
    borderRadius: '6px',
    fontSize: '0.95rem',
    color: '#3a2218',
    background: '#fff',
    boxSizing: 'border-box',
    outline: 'none',
  },
  radioCard: {
    display: 'block',
    padding: '0.85rem 1rem',
    borderRadius: '8px',
    cursor: 'pointer',
    background: '#faf5ef',
  },
  radioLabel: {
    fontSize: '0.95rem',
    fontWeight: 600,
    color: '#3a2218',
  },
  radioDesc: {
    fontSize: '0.8rem',
    color: '#8b7355',
    marginTop: '0.15rem',
  },
  autopayRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.5rem',
    marginTop: '0.75rem',
    paddingTop: '0.75rem',
    borderTop: '1px solid #e8e0d4',
    cursor: 'pointer',
  },
  autopayText: {
    fontSize: '0.85rem',
    color: '#4a3520',
    lineHeight: 1.4,
  },
  payButton: {
    marginTop: '1.25rem',
    width: '100%',
    padding: '0.85rem',
    background: '#2d6a4f',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    fontSize: '1rem',
    fontWeight: 600,
    cursor: 'pointer',
    letterSpacing: '0.02em',
  },
  paidBanner: {
    padding: '2rem',
    textAlign: 'center',
    background: '#d8f3dc',
    borderBottom: '1px solid #b7e4c7',
  },
  footer: {
    textAlign: 'center',
    padding: '1.5rem 2rem',
  },
};

export default styles;
