// Inline-style objects shared by ProposalView and its extracted sections.
//
// Hybrid strategy (2026-05-08): styles.js stays as inline-style objects, but
// values updated to the Apothecary Press palette (parchment scroll on chalkboard,
// IM Fell English, brass details). New visual structures (hero with wax-seal,
// workshop-bench sign-and-pay card, payment tablets, sticky desktop rail, paid
// success card) live as new .proposal-* / .sign-pay-* / .payment-tablet classes
// in client/src/index.css and are added to the JSX with className. This keeps
// the high-stakes Stripe/sign code paths untouched while letting the new chrome
// live in proper CSS. Full migration is deferred to a post-cutover follow-up.

const styles = {
  page: {
    minHeight: '100dvh',
    background: 'var(--chalkboard)',
    backgroundImage: 'url("/static/chalkboard_background.png")',
    backgroundSize: '1200px auto',
    backgroundRepeat: 'repeat',
    padding: '40px 16px 64px',
    fontFamily: 'var(--font-body)',
  },
  header: {
    textAlign: 'center',
    padding: '0 0 18px',
    borderBottom: '1px solid rgba(184,146,74,0.4)',
    marginBottom: 22,
  },
  brand: {
    fontFamily: 'var(--font-display)',
    fontSize: '1.1rem',
    color: 'var(--cream-text)',
    letterSpacing: '0.04em',
    margin: 0,
  },
  tagline: {
    color: 'var(--brass)',
    marginTop: 4,
    fontSize: '10px',
    letterSpacing: '0.32em',
    textTransform: 'uppercase',
    fontFamily: 'var(--font-display)',
  },
  // Sealed-scroll body sections sit on a parchment card; see .proposal-scroll
  // in index.css for the wrapper. styles.section provides the inner padding.
  section: {
    padding: '22px 26px',
    borderBottom: '1px solid rgba(184,146,74,0.32)',
  },
  sectionTitle: {
    fontFamily: 'var(--font-display)',
    fontSize: '1.4rem',
    color: 'var(--deep-brown)',
    margin: '0 0 14px',
    letterSpacing: '0.015em',
    fontWeight: 400,
  },
  heading: {
    fontFamily: 'var(--font-display)',
    fontSize: '1.5rem',
    color: 'var(--cream-text)',
    fontWeight: 400,
  },
  detailGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '0.5rem 1.5rem',
  },
  detailItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    padding: '8px 0',
    borderBottom: '1px dotted rgba(28,22,16,0.22)',
  },
  detailLabel: {
    fontSize: '10.5px',
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.18em',
    fontFamily: 'var(--font-display)',
  },
  detailValue: {
    fontSize: '14.5px',
    color: 'var(--deep-brown)',
    fontWeight: 400,
  },
  includesList: {
    margin: 0,
    padding: 0,
    listStyle: 'none',
    color: 'var(--deep-brown)',
  },
  includesItem: {
    fontSize: '14px',
    marginBottom: '6px',
    lineHeight: 1.55,
  },
  contractScroll: {
    maxHeight: '180px',
    overflowY: 'hidden',
    background: 'transparent',
    border: 'none',
    borderRadius: 0,
    padding: 0,
    position: 'relative',
  },
  contractText: {
    fontSize: '0.875rem',
    color: 'var(--deep-brown)',
    lineHeight: 1.6,
    marginBottom: '0.65rem',
    marginTop: 0,
  },
  contractList: {
    margin: '0 0 0.65rem 0',
    padding: '0 0 0 1.2rem',
    color: 'var(--deep-brown)',
  },
  contractListItem: {
    fontSize: '0.875rem',
    lineHeight: 1.6,
    marginBottom: '0.3rem',
  },
  agreementHeading: {
    fontFamily: 'var(--font-display)',
    fontSize: '1.02rem',
    fontWeight: 600,
    color: 'var(--deep-brown)',
    letterSpacing: '0.01em',
    margin: '1.1rem 0 0.5rem',
  },
  paymentSummary: {
    background: 'rgba(184,146,74,0.08)',
    border: '1px solid rgba(184,146,74,0.4)',
    borderRadius: '6px',
    padding: '0.25rem 1rem',
  },
  paymentRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.65rem 0',
    borderBottom: '1px solid rgba(184,146,74,0.25)',
  },
  paymentLabel: {
    fontSize: '0.85rem',
    color: 'var(--text-muted)',
    fontFamily: 'var(--font-display)',
    letterSpacing: '0.04em',
  },
  paymentValue: {
    fontSize: '0.95rem',
    fontWeight: 600,
    color: 'var(--deep-brown)',
    fontFamily: 'var(--font-display)',
  },
  ctaButton: {
    display: 'block',
    width: '100%',
    marginTop: '1.25rem',
    padding: '14px 20px',
    background: 'var(--amber)',
    color: 'var(--cream-text)',
    border: 'none',
    borderRadius: '8px',
    fontSize: '0.95rem',
    fontWeight: 500,
    cursor: 'pointer',
    letterSpacing: '0.06em',
    fontFamily: 'var(--font-display)',
    boxShadow: '0 2px 10px rgba(29,140,137,0.32)',
  },
  signPaySection: {
    padding: 0,
    background: 'transparent',
    borderBottom: 'none',
  },
  signPayTitle: {
    fontFamily: 'var(--font-display)',
    fontSize: '1.5rem',
    color: 'var(--cream-text)',
    marginBottom: '4px',
    marginTop: 0,
    letterSpacing: '0.015em',
    fontWeight: 400,
  },
  label: {
    display: 'block',
    fontSize: '11px',
    fontWeight: 400,
    color: 'var(--brass)',
    textTransform: 'uppercase',
    letterSpacing: '0.18em',
    marginBottom: '8px',
    fontFamily: 'var(--font-display)',
  },
  nameInput: {
    width: '100%',
    padding: '12px 14px',
    border: '1px solid rgba(28,22,16,0.22)',
    borderRadius: '6px',
    fontSize: '0.95rem',
    color: 'var(--deep-brown)',
    background: 'var(--paper)',
    boxSizing: 'border-box',
    outline: 'none',
    fontFamily: 'var(--font-body)',
  },
  radioCard: {
    display: 'block',
    padding: '14px 16px',
    borderRadius: '8px',
    cursor: 'pointer',
    background: 'var(--paper)',
  },
  radioLabel: {
    fontSize: '0.95rem',
    fontWeight: 500,
    color: 'var(--deep-brown)',
    fontFamily: 'var(--font-display)',
  },
  radioDesc: {
    fontSize: '0.8rem',
    color: 'var(--text-muted)',
    marginTop: '2px',
  },
  autopayRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '8px',
    marginTop: '10px',
    paddingTop: '10px',
    borderTop: '1px dashed rgba(29,140,137,0.6)',
    cursor: 'pointer',
  },
  autopayText: {
    fontSize: '0.85rem',
    color: 'var(--deep-brown)',
    lineHeight: 1.45,
  },
  payButton: {
    marginTop: '1.25rem',
    width: '100%',
    padding: '14px 20px',
    background: 'var(--amber)',
    color: 'var(--cream-text)',
    border: 'none',
    borderRadius: '8px',
    fontSize: '0.95rem',
    fontWeight: 500,
    cursor: 'pointer',
    letterSpacing: '0.06em',
    fontFamily: 'var(--font-display)',
    boxShadow: '0 2px 10px rgba(29,140,137,0.32)',
  },
  paidBanner: {
    padding: '32px 24px',
    textAlign: 'center',
    background: 'rgba(45,107,90,0.18)',
    border: '1px solid rgba(45,107,90,0.5)',
    borderRadius: '8px',
    marginTop: '22px',
  },
  footer: {
    textAlign: 'center',
    padding: '24px 16px',
    color: 'var(--brass)',
    fontFamily: 'var(--font-display)',
    fontSize: '11px',
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
  },
};

export default styles;
